---
title: "CLUSTERING_FINAL177"
output: pdf_document
date: "2025-03-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(mice)
library(ggplot2)
library(cluster)
library(factoextra)
```

## R Markdown


```{r}
imputed <- read.csv('complete_dataset_177.csv') %>% dplyr::select(-c(X))
cols_to_factor <- c('RIDRETH3', 'RIAGENDR', 'DMQMILIZ', 'DMDBORN4', 'DMDEDUC2', 'DMDMARTZ', 'DMDHHSIZ')

for (col in cols_to_factor) {
  imputed[col] <- factor(imputed[[col]])
}
for_clustering <- imputed %>% dplyr::select('RIDRETH3', 'RIAGENDR', 'DMQMILIZ', 'DMDBORN4', 'DMDEDUC2', 'DMDMARTZ', 'DMDHHSIZ', 'RIDAGEYR', 'INDFMPIR')
```


```{r}
encoded_cat <- model.matrix(~.-1, data = for_clustering)
encoded_cat[,c(24,25)] <- scale(encoded_cat[,c(24,25)])
```

```{r}
fviz_nbclust(encoded_cat, kmeans, method='silhouette', k.max = 25)
fviz_nbclust(encoded_cat, kmeans, method='wss', k.max = 25)

```

```{r}
centers4 <- kmeans(encoded_cat, centers = 7, iter.max = 50, nstart = 75) 
clustered_df <- as.data.frame(encoded_cat)
clustered_df$clusters <- centers4$cluster
clustered_df$PHQ_score <- imputed$PHQ9_TOTAL

```


```{r}
# Visualize depression scores by cluster
ggplot(clustered_df, aes(x = factor(clusters), y = PHQ_score, fill = factor(clusters))) +
  geom_boxplot(outlier.shape = NA) +
  labs(title = "Depression Scores by Demographic Cluster",
       x = "Cluster",
       y = "Depression Score") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 12),
        legend.position = 'none')
```


```{r}
ggplot(clustered_df, aes(PHQ_score, fill = factor(clusters))) +
  geom_density(alpha = .7) +
  labs(title = "Depression Scores by Demographic Cluster",
       x = "Depression Scores",
       y = "Density") +
  theme_minimal() + 
  guides(fill = guide_legend(title = 'Cluster'))
```



```{r}
clustered_df %>% dplyr::group_by(factor(clusters)) %>% summarise(
    mean_PHQ9 = mean(PHQ_score),
    median_PHQ9 = median(PHQ_score),
    sd_PHQ9 = sd(PHQ_score),
    n = n()
  )
```




```{r}
summary(aov(PHQ_score ~ factor(clusters), data = clustered_df))
```











